# Generated by Django 4.1.5 on 2023-01-28 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePersonalInfo',
            fields=[
                ('personal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('department', models.CharField(max_length=200)),
                ('martial_status', models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'UnMarried'), ('Divorced', 'Divorced'), ('Widow', 'Widow')], max_length=200)),
                ('caste', models.CharField(choices=[('OPEN', 'OPEN'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], max_length=200)),
                ('City', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
